FROM arm32v7/node:latest
LABEL maintainer="dragonchaser <matrix-feeder@datenschmutz.space>"
COPY qemu-arm-static /usr/bin
COPY . /matrix-feeder
WORKDIR /matrix-feeder
RUN npm install
CMD node feeder.js

